### ISSUE TITLE
Impossible d'installer le module

### ISSUE THREAD

**Issue by Adjenz** [tducret/ingdirect-python#2]
Bonjour,

Tout d'abord merci pour ce super travail et pour le site web très pédagogique.

J'essaye d'installer ce module mais je reçois les erreurs ci-dessous. J'ai bien rempli les requirements et testé avec un Python 3.5, 3.6, 3.7 et 3.8.

`    ERROR: Command errored out with exit status 1:
     command: /home/adrien/PycharmProjects/Python/ING/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-zpp9k40n/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-zpp9k40n/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-syqzjjlf
         cwd: /tmp/pip-req-build-zpp9k40n/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zpp9k40n/setup.py", line 23, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-req-build-zpp9k40n/setup.py", line 23, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by tducret** [comment]
Bonjour @Screamus57 , je viens de pousser une nouvelle version, qui simplifie la récupération des requirements dans `setup.py`.
J'avais déjà remarqué des problèmes avec d'autres projets, en fonction de la version de pip utilisée.
Pouvez-vous essayer d'installer cette version svp?
`pip install ingdirect==0.1.2`
